name: Release
 
on:
  release:
  types: [published]

env:
  DOTNET_VERSION: '9.x'
  SOLUTION_PATH: 'TSqlSharp.sln'
  PROJECT_PATH: 'src/TSqlSharp.csproj'
  PACKAGE_NAME: 'TSqlSharp.Formatter'


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }}
          --configuration Release
          --no-restore

      - name: pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --output ./artifacts/${{ env.PACKAGE_NAME }}.${{ github.event.release.tag_name }}.nupkg

      - name: push
        run: dotnet nuget push ${{ env.PACKAGE_NAME }}.${{ github.event.release.tag_name }}.nupkg -k ${{ secrets.NUGET_API_KEY }}
          
      
      